name: Publish Site

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: setup hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.159.2'

      - name: build
        run: hugo build --minify

      - uses: actions/upload-pages-artifact@v4
        with: 
          path: ./public

      - uses: actions/deploy-pages@v5
